### ISSUE TITLE
Cannot remove SW/AU flag on windows

### ISSUE THREAD

**Issue by AlexDanault** [Alcyon-Dev/vscode-ext-git-skip#10]
When unflagging a file, the file path is missingthe drive letter on Windows, resulting in an invalid command:

`Error calling git command "C:\Program Files\Git\cmd\git.exe update-index --no-skip-worktree \Projects\GitSkipDemo\README.md" : spawn C:\Program Files\Git\cmd\git.exe ENOENT -`

**Comment by npmrun** [comment]
same issue

**Comment by AlexDanault** [comment]
I'll check into this.

**Comment by AlexDanault** [comment]
@npmrun Version 0.5.3 is out and fixes this bug. Thanks for bumping this issue !
