### ISSUE TITLE
"Assume Unchanged" should be moved to the context menu on files and folders in Explorer

### ISSUE THREAD

**Issue by ADTC** [Alcyon-Dev/vscode-ext-git-skip#3]
As per [the great blog post](https://automationpanda.com/2018/09/19/ignoring-files-with-git/):

> assume-unchanged assumes that the user will **not** change the file. **The intention is different.** Large projects using slow file systems may gain significant performance optimizations by marking unused directories as assume-unchanged.

Since "Assume Unchanged" makes more sense for _unchanged_ files, it should be in the files and folders context menu in Explorer (when right-clicking a file or folder).

The Git Source Control panel should only have "Skip Worktree" since it is for ignoring changes but "Assume Unchanged" is not.

**Comment by AlexDanault** [comment]
Good point, I agree that assume unchanged should be available in the Explorer.

But I'll likely leave it available in the Git explorer too, as it can still be useful there and also adds visibility to that feature.

**Comment by AlexDanault** [comment]
I have a version in progress that adds the context menu to the eplorer, can hadle multi-selection, but NOT folders for now.

git's assume-unchanged doesn't handle folders at all, so this will require some thinking, otherwise there will be edge cases all over the place.

**Comment by ADTC** [comment]
Yeah, git has no notion of folders. Remember that we can't commit empty folders. There's nothing inside git to represent folders other than the path of a file.

So I guess it will have to be recursively finding all the files in the given folder and all subfolders as deep as possible.

**Comment by AlexDanault** [comment]
Yeah, that's the challendge. Finding the files is easy, but it won't be user friendly.

If a user can assume unchange a folder, they'll expect the ability to undo that folder in a single operation, but what'll they'll find in the git skip view is a ton of files they have to undo in batch.

Also they'll expect new files in an assume-unchanged folder to be ignored, but they wont, since only the current files were tagged. Sure, untracked files can't be tagged, but it'll still feel weird.

As I said, next update will add the command to the explorer context, for files. Later, I'll rethink how I could handle the folders. Maybe by displaying a treeview in the git skip list, that would be practical.

**Comment by AlexDanault** [comment]
Version 0.3.0 is out now, with the basic feature of having "Assume unchanged" available in the explorer context menu. It's not perfect, but it's a start :)

Thanks !

**Comment by ADTC** [comment]
How about if you also add the folder into `.git/info/exclude`?  Then maybe you do something like: 

If you find a folder in `.git/info/exclude` or `.gitignore` and **all** tracked files in the folder (deeply) are AU, then show the folder as AU. If there are **some** tracked files in the folder that aren't AU then show the AU-marked files separately.

Clicking undo on folder will not only undo AU of all tracked files in the folder but also remove the folder from `.git/info/exclude` (but leave it if it's in `.gitignore`).

Running AU on a folder will add AU on all the files in it (deeply) and also add the folder itself to `.git/info/exclude` (if it's not already in `.gitignore`).

You may need to warn to the user that any new files added to the folder will be completely ignored by Git, and not just "tracked but AU". Anyway I think.it matches user expectation when you AU an entire folder. You're assuming the folder itself won't change and that includes adding new files in it.

(This is an untested hypothesis based on what I know of these features. But I think it should work and I believe the operations are idempotent and safe. Your extension doesn't need to track or remember anything by itself, and it is just leveraging two separate Git features into a combined feature to AU folders.)

Anyway if it's too complex, maybe there's no need to add folders for now. Just open a separate pinned issue for gathering interest in the potential feature.

**Comment by ADTC** [comment]
Just in case you're reading email notification, I made a lot of edits to the last comment so you may want to view it in GitHub.

**Comment by ADTC** [comment]
The menu option on files appear to be working well. Just tested it.

**Comment by AlexDanault** [comment]
I'll close this for now, I'll keep for later the idea on how to assume unchanged full folders.
