### ISSUE TITLE
Git Skip panel should show Skip Worktree items and Assumed Unchanged items separately

### ISSUE THREAD

**Issue by ADTC** [Alcyon-Dev/vscode-ext-git-skip#4]
It seems they are now combined into a single list. There should be collapsible sections (similar to "Changes" and "Staged Changes" sections in Source Control) named "Skip Worktree" and "Assume Unchanged".

Notes:
* A section with no files is hidden completely. (No empty section.)
* Header of the visible section should be visible even if there's only one section visible. This is to know whether it's "Skip Worktree" or "Assume Unchanged".

**Comment by AlexDanault** [comment]
This is how the extension was on the first release, but I got feedback that it took too much screen space.

I'll see if I can make it into an option.

**Comment by ADTC** [comment]
You can also consider adding some icon or indication to distinguish the two.

**Comment by ADTC** [comment]
About this, the separate collapsible sections will be better for me. Maybe it could be an option.

Otherwise an idea: the exact location of the Undo button could show an icon to indicate "assume unchanged" - maybe a pencil with a perpendicular line through it. The icon would become Undo button upon hover or selection.

To reduce visual clutter, "skip worktree" could have no icon. I assume people will be using this option more often than "assume unchanged". _Skip_ icons tend to be more abstract anyway.

**Comment by AlexDanault** [comment]
Coming soon:
![image](https://github.com/Alcyon-Dev/vscode-ext-git-skip/assets/4428772/0afad01f-dd96-4947-a18d-84d3fa553926)

**Comment by AlexDanault** [comment]
Should now be fixed in 0.4.1. If you can confirm this works for you, I'll close this issue.

**Comment by ADTC** [comment]
I suggest rolling out icons for this in future but I think this is good enough for now. :)

Works. Closing.
