### ISSUE TITLE
Can't select multiple entries in Git Skip panel to undo them all in one click

### ISSUE THREAD

**Issue by ADTC** [Alcyon-Dev/vscode-ext-git-skip#5]
Can't select multiple entries in Git Skip panel to undo them all in one click. I discovered this while recording the video for the other issue.

**Comment by AlexDanault** [comment]
Should now be fixed in 0.4.1. If you can confirm this works for you, I'll close this issue.

**Comment by ADTC** [comment]
This works. Thanks!
