### ISSUE TITLE
Feature Request: Clicking on an item in Git Skip panel could open the diff view (Working Tree) instead of the file

### ISSUE THREAD

**Issue by ADTC** [Alcyon-Dev/vscode-ext-git-skip#6]
I have tested and found that the Working Tree (diff) view of the file will continue to show the changes which are skipped in worktree or assumed unchanged. It will be nice if clicking on a file in Git Skip panel would show this view again instead of opening the file. I'd like to check the diff that's skipped or assumed unchanged.

It's useful when we make changes in a file which is skipped, and we want to stage just those changes (while continuing to skip other changes). Right now we have to unskip, stage selectively, (possibly commit too, not sure), and skip again. But if we can directly open the Working Tree view, we can simply stage from it by selecting and clicking "Stage Selected Ranges" in the context menu. So this will be useful.

Similar to the Source Control panel, you can have a button (near the Undo button) which opens the file directly. (The icon is a paper with a  U-turned arrow pointing to it. I think it makes sense because it's consistent with the Source Control panel.

<img width="244" alt="image" src="https://github.com/Alcyon-Dev/vscode-ext-git-skip/assets/6047296/08c3cdab-5ff1-45fd-929b-f3222bc622f7">

PS: I can't find any other feature in VS Code that would let me open the Working Tree view of any file from the Explorer panel. If I could, this would not have been so critical. It seems right now the only way to open it is via the Source Control panel, and I can only do it if it's showing the file in "Changes".

**Comment by AlexDanault** [comment]
Should now be fixed in 0.4.1. If you can confirm this works for you, I'll close this issue.

**Comment by ADTC** [comment]
This doesn't work as I described in the issue. Now it doesn't do anything for me when I click the file name (I expected to see the diff). It opens the file as normal when I click the Open File icon.

I've tried both AU and SW. There are no errors in Output.

**Comment by AlexDanault** [comment]
Alright, I'll look into it. On my machine it works correctly in all scenarios. Can you decribe your current setup to me (mostly what OS you are using, and any detail you think might help) ?

**Comment by ADTC** [comment]
https://github.com/Alcyon-Dev/vscode-ext-git-skip/assets/6047296/dc496481-e8bb-49c0-9fd6-2d90d6300b5d

```
Version: 1.87.2
Commit: 863d2581ecda6849923a2118d93a088b0745d9d6
Date: 2024-03-08T15:20:57.520Z
Electron: 27.3.2
ElectronBuildId: 26836302
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Darwin arm64 23.4.0 (this is MacOS Sonoma 14.4 (23E214) - IDK about the Darwin thing)
```

Let me know if you need to know anything else. :)

**Comment by AlexDanault** [comment]
It looks like it only works when the extension is in dev mode, I'll revisit this soon.

**Comment by ADTC** [comment]
Hmm, any luck for this? Viewing the diff would be nice.

**Comment by AlexDanault** [comment]
I'll give it a try this week, thanks for bumping the issue.

If anyone knows how to open a `git diff` view from a resource URI, nothing I tried works yet :(

https://github.com/Alcyon-Dev/vscode-ext-git-skip/blob/91ac5330b1ebfbe449e8588bd53da0720d502f5a/src/provider.ts#L98-L101

**Comment by AlexDanault** [comment]
This is now fixed in 0.6.0 :)

**Comment by ADTC** [comment]
Thank you. I appreciate it. Sorry I couldn't be of help. I will try this out later.

Edit: It's working! 🙂

**Comment by AlexDanault** [comment]
No problem @ADTC , enjoy the feature :)
